subdirs: $(SUBDIRS)
$(SUBDIRS):
	@flock $@ $(MAKE) -C $@

all: $(subdirs)

SUBDIRS_CLEAN = $(addsuffix .clean,$(SUBDIRS))
clean: $(SUBDIRS_CLEAN)
$(SUBDIRS_CLEAN): %.clean:
	@flock $* $(MAKE) -C $* clean

.PHONY: all clean $(SUBDIRS)