version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
      - "9000:9000"
      - "2222:2222"
    networks:
      - os_share_network
    volumes:
      - ../:/root/SynestiaOS
    privileged: true


networks:
  os_share_network:
