if (PLATFORM STREQUAL pi2)
    set(SynestiaPlatform pi2)
    set(SynestiaPlatformMacro RASPI2)
elseif (PLATFORM STREQUAL pi3)
    set(SynestiaPlatform pi3)
    set(SynestiaPlatformMacro RASPI3)
elseif (PLATFORM STREQUAL pi4)
    set(SynestiaPlatform pi4)
    set(SynestiaPlatformMacro RASPI4)
else ()
    message(WARNING "unexpected PLATFORM ${PLATFORM}, using default value \"pi2\"")
    set(SynestiaPlatform pi2)
endif ()

message(STATUS "SynestiaPlatform is ${SynestiaPlatform}")
