set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR arm)

# NOTE: change this to your arm compiler path
set(CMAKE_FIND_ROOT_PATH /Users/shifu.wu/gcc-arm-none-eabi-9-2020-q2-update/bin)

set(CMAKE_C_COMPILER ${CMAKE_FIND_ROOT_PATH}/arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER ${CMAKE_FIND_ROOT_PATH}/arm-none-eabi-g++)

set(CMAKE_CROSSCOMPILING_EMULATOR qemu-system-arm)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
